import { world, system } from "@minecraft/server";
import { registerLeavesComponent } from "./blocks/leaves.js";
import { registerInvisibleComponent } from "./blocks/invisible.js";
import { registerCurtainComponent } from "./blocks/curtain.js";
import { registerWoodComponent } from "./blocks/wood.js";
import { registerFenceComponent } from "./blocks/fence.js";
import { registerSaplingComponent } from "./blocks/sapling.js";
import { registerWallComponent } from "./blocks/wall.js";
import { registerButtonComponent } from "./blocks/button.js";
import { registerPressurePlateComponent } from "./blocks/pressure_plate.js";
import { registerStairsComponent } from "./blocks/stairs.js";
import { registerGeyserComponent, initializeGeyser } from "./blocks/geyser.js";
import { registerSandstoneComponent } from "./blocks/sandstone_slab.js";
import { registerStoneSlabComponent } from "./blocks/stone_slab.js";
import { registerGaiaFurnaceComponent } from "./blocks/furnaces/GaiaFurnace.js";
import { registerPurifierComponent } from "./blocks/purifier.js";
import { registerRestructurerComponent } from "./blocks/restructurer.js";
import { registerGlitteringFireComponent } from "./blocks/glittering_fire.js";
import { registerCrudeStorageCrateComponent } from "./blocks/crates/crude_storage_crate.js";
import { registerMegaStorageCrateComponent } from "./blocks/crates/mega_storage_crate.js";
import { initializeLightMixin } from "./mixins/LightMixin.js";
import { initializeSkybox } from "./mixins/skybox.js";
import { PortalManager } from "./API/lib/PortalLib.js";
import { initializeDestructionHandlers } from "./systems/destruction_handler.js";
import { initializeEventManager } from "./systems/event_manager.js";
import { initializeScriptEvents } from "./systems/scriptevents.js";
import { registerFluidComponent } from "./fluids/fluids.js";
import { registerCustomTool } from "./durability.js";
import { DimensionSystem } from "./world/Gaia.js";
import "./world/CoordinateDisplay.js";
import "./world/TerrainPatching.js";
import "./systems/enchantments.js";
import "./blocks/mineral_centrifuge.js";
import "./blocks/arcane_library.js";
import "./blocks/purifier.js";
import "./blocks/restructurer.js";

// Initialize systems
initializeDestructionHandlers();
initializeEventManager();
initializeScriptEvents();
initializeGeyser();
initializeLightMixin();
initializeSkybox();
registerCustomTool();

system.beforeEvents.startup.subscribe(({ blockComponentRegistry }) => {
    registerLeavesComponent({ blockComponentRegistry });
    registerInvisibleComponent({ blockComponentRegistry });
    registerCurtainComponent({ blockComponentRegistry });
    registerWoodComponent({ blockComponentRegistry });
    registerFenceComponent({ blockComponentRegistry });
    registerSaplingComponent({ blockComponentRegistry });
    registerWallComponent({ blockComponentRegistry });
    registerButtonComponent({ blockComponentRegistry });
    registerPressurePlateComponent({ blockComponentRegistry });
    registerStairsComponent({ blockComponentRegistry });
    registerGeyserComponent({ blockComponentRegistry });
    registerSandstoneComponent({ blockComponentRegistry });
    registerStoneSlabComponent({ blockComponentRegistry });
    registerGaiaFurnaceComponent({ blockComponentRegistry });
    registerPurifierComponent({ blockComponentRegistry });
    registerRestructurerComponent({ blockComponentRegistry });
    registerGlitteringFireComponent();
    registerCrudeStorageCrateComponent({ blockComponentRegistry });
    registerMegaStorageCrateComponent({ blockComponentRegistry });
    registerFluidComponent({ blockComponentRegistry });
});
