stopsound @s music.game_and_wild_equal_chance
stopsound @s music.game.basalt_deltas
stopsound @s music.game_and_wild_favor_game
stopsound @s music.game.creative
stopsound @s music.game.credits
stopsound @s music.game.crimson_forest
stopsound @s music.game.deep_dark
stopsound @s music.game.dripstone_caves
stopsound @s music.game.end
stopsound @s music.game.endboss
stopsound @s music.game.frozen_peaks
stopsound @s music.game
stopsound @s music.game.grove
stopsound @s music.game.nether_wastes
stopsound @s music.game.jagged_peaks
stopsound @s music.game.lush_caves
stopsound @s music.game.swamp_music
stopsound @s music.game.meadow
stopsound @s music.menu
stopsound @s music.game.nether
stopsound @s music.game.snowy_slopes
stopsound @s music.game.soulsand_valley
stopsound @s music.game.stony_peaks
stopsound @s music.game.water